package policy

import (
	"fmt"
	"strings"
)

func GenerateAuditCertificateHTML(caseID, vendorName, verdict string, violations []string) string {
	borderColor := "#38a169"
	headerColor := "#276749"
	if verdict == "REVIEW" {
		borderColor = "#e53e3e"
		headerColor = "#c53030"
	}

	var violationList string
	if len(violations) > 0 {
		var items []string
		for _, v := range violations {
			items = append(items, fmt.Sprintf("<li style=\"color:#c53030; margin-bottom: 4px;\">%s</li>", v))
		}
		violationList = fmt.Sprintf("<ul>%s</ul>", strings.Join(items, ""))
	} else {
		violationList = "<p style=\"color:#276749;\">✓ All compliance policies and historical variance checks passed cleanly.</p>"
	}

	return fmt.Sprintf(`
	<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 10px auto; border: 2px solid %s; border-radius: 8px; padding: 20px; background-color: #ffffff; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
		<div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #edf2f7; padding-bottom: 10px;">
			<h2 style="color: %s; margin: 0; font-size: 1.3rem;">🛡️ Governance Audit Certificate</h2>
			<span style="background: %s; color: white; padding: 4px 12px; border-radius: 12px; font-weight: bold; font-size: 0.85rem;">%s</span>
		</div>
		<div style="margin-top: 15px; font-size: 0.95rem; color: #2d3748;">
			<p style="margin: 4px 0;"><strong>Audit Case ID:</strong> %s</p>
			<p style="margin: 4px 0;"><strong>Vendor Name:</strong> %s</p>
			<p style="margin: 4px 0;"><strong>Engine Status:</strong> Deterministic Policy Enforcement Complete</p>
		</div>
		<div style="margin-top: 15px; background: #f7fafc; padding: 12px; border-radius: 6px;">
			<h4 style="margin: 0 0 8px 0; color: #4a5568;">Policy & Historical Variance Findings:</h4>
			%s
		</div>
		<div style="margin-top: 15px; font-size: 0.8rem; color: #a0aec0; text-align: right;">
			Generated by Go Compliance & Governance Agent (A2A Protocol)
		</div>
	</div>
	`, borderColor, headerColor, headerColor, verdict, caseID, vendorName, violationList)
}
